In [51]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)
import warnings
warnings.filterwarnings('ignore')

pasta_dados = '../dados/'

df_acidentes = pd.read_csv(pasta_dados + '/acidentes_de_transportes.csv')
df_populacao = pd.read_csv(pasta_dados + 'simu_carteira_populacao.csv')

In [52]:
df_acidentes

,Código IBGE,ano,Região,Município,Pedestre_mortes,Ciclista_mortes,Motociclista_mortes,Ocup_triciclo_motor_mortes,Ocup_automovel_mortes,Ocup_caminhonete_mortes,Ocup_veic_transp_pesado_mortes,Ocup_onibus_mortes,Outros_mortes,Populacao,total_mortes,taxa_mun_mortes,taxa_mun_pedestre_mortes,taxa_mun_ciclista_mortes,taxa_mun_motociclista_mortes,taxa_mun_automovel_mortes,taxa_mun_veiculo_pesado_mortes,taxa_mun_onibus_mortes,taxa_mun_outros_mortes,mun_MUNNOME,mun_MUNNOMEX,mun_AMAZONIA,mun_FRONTEIRA,mun_CAPITAL,mun_LATITUDE,mun_LONGITUDE,mun_ALTITUDE,mun_AREA,mun_codigo_adotado,uf_SIGLA_UF,uf_CODIGO_UF,uf_NOME_UF,uf_REGIAO,mun_coordenadas,Pedestre_feridos,Ciclista_feridos,Motociclista_feridos,Ocup_triciclo_motor_feridos,Ocup_automovel_feridos,Ocup_caminhonete_feridos,Ocup_veic_transp_pesado_feridos,Ocup_onibus_feridos,Outros_feridos,total_feridos,taxa_mun_feridos,taxa_mun_pedestre_feridos,taxa_mun_ciclista_feridos,taxa_mun_motociclista_feridos,taxa_mun_automovel_feridos,taxa_mun_veiculo_pesado_feridos,taxa_mun_onibus_feridos,taxa_mun_outros_feridos
0,1100015,2010,N,Alta Floresta D'Oeste,2,0,5,0,0,0,0,0,0,24392,7.0,28.697900,8.199400,0.000000,20.498500,0.000000,0.000000,0.000000,0.000000,Alta Floresta D'Oeste,ALTA FLORESTA D'OESTE,S,S,N,-11.929,-61.996,350.0,7066.702,110001,RO,11,RONDONIA,Norte,"-11.92900,-61.99600",0,0,13,0,0,0,0,0,0,13.0,53.296200,0.000000,0.000000,53.296200,0.000000,0.000000,0.000000,0.000000
1,1100023,2010,N,Ariquemes,0,1,2,0,0,0,0,1,29,90353,33.0,36.523400,0.000000,1.106800,2.213500,0.000000,0.000000,1.106800,32.096300,Ariquemes,ARIQUEMES,S,N,N,-9.913,-63.041,142.0,4426.558,110002,RO,11,RONDONIA,Norte,"-9.91300,-63.04100",0,1,37,0,1,1,0,0,3,43.0,47.591100,0.000000,1.106800,40.950500,2.213500,0.000000,0.000000,3.320300
2,1100031,2010,N,Cabixi,0,0,0,0,0,0,0,0,0,6313,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,Cabixi,CABIXI,S,S,N,-13.492,-60.545,230.0,1314.355,110003,RO,11,RONDONIA,Norte,"-13.49200,-60.54500",0,0,0,0,0,0,0,0,0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,1100049,2010,N,Cacoal,2,1,17,0,4,0,0,0,2,78574,26.0,33.089800,2.545400,1.272700,21.635700,5.090700,0.000000,0.000000,2.545400,Cacoal,CACOAL,S,N,N,-11.438,-61.448,200.0,3792.638,110004,RO,11,RONDONIA,Norte,"-11.43800,-61.44800",50,1,5,0,0,0,0,0,1,57.0,72.543100,63.634300,1.272700,6.363400,0.000000,0.000000,0.000000,1.272700
4,1100056,2010,N,Cerejeiras,3,0,1,0,0,0,0,0,0,17029,4.0,23.489300,17.617000,0.000000,5.872300,0.000000,0.000000,0.000000,0.000000,Cerejeiras,CEREJEIRAS,S,S,N,-13.189,-60.812,277.0,2783.305,110005,RO,11,RONDONIA,Norte,"-13.18900,-60.81200",0,1,0,0,0,0,0,0,0,1.0,5.872300,0.000000,5.872300,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55695,5222005,2019,CO,Vianópolis,1,0,1,0,0,0,0,0,2,13863,4.0,28.853783,7.213446,0.000000,7.213446,0.000000,0.000000,0.000000,14.426892,Vianópolis,VIANOPOLIS,N,N,N,-16.742,-48.516,1002.0,954279.000,522200,GO,52,GOIAS,Centro-Oeste,"-16.742,-48.516",0,0,0,0,0,0,0,0,0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
55696,5222054,2019,CO,Vicentinópolis,0,0,0,0,2,0,0,0,2,8743,4.0,45.750886,0.000000,0.000000,0.000000,22.875443,0.000000,0.000000,22.875443,Vicentinópolis,VICENTINOPOLIS,N,N,N,-17.735,-49.806,646.0,737251.000,522205,GO,52,GOIAS,Centro-Oeste,"-17.735,-49.806",0,0,0,0,0,0,0,0,0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
55697,5222203,2019,CO,Vila Boa,0,0,1,0,6,0,1,0,0,6171,8.0,129.638632,0.000000,0.000000,16.204829,97.228974,16.204829,0.000000,0.000000,Vila Boa,VILA BOA,N,N,N,-15.038,-47.059,0.0,1060170.000,522220,GO,52,GOIAS,Centro-Oeste,"-15.038,-47.059",0,0,0,0,0,0,0,0,0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
55698,5222302,2019,CO,Vila Propício,0,0,0,0,1,0,0,0,2,5821,3.0,51.537537,0.000000,0.000000,0.000000,17.179179,0.000000,0.000000,34.358358,Vila Propício,VILA PROPICIO,N,N,N,-15.457,-48.889,744.0,2181575.000,522230,GO,52,GOIAS,Centro-Oeste,"-15.457,-48.889",0,0,0,0,0,0,0,0,0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
55699,5300108,2019,CO,Brasília,107,20,97,0,87,6,6,1,14,3015268,338.0,11.209617,3.548607,0.663291,3.216961,2.885316,0.198987,0.033165,0.464304,Brasília,BRASILIA,N,N,S,-15.780,-47.930,1171.0,5801937.000,530010,DF,53,DISTRITO FEDERAL,Centro-Oeste,"-15.78,-47.93",600,309,1182,7,353,9,20,10,145,2635.0,87.388584,19.898729,10.247845,39.200496,11.707085,0.663291,0.331645,4.808859

In [53]:
df_acidentes.columns

Index(['Código IBGE', 'ano', 'Região', 'Município', 'Pedestre_mortes',
       'Ciclista_mortes', 'Motociclista_mortes', 'Ocup_triciclo_motor_mortes',
       'Ocup_automovel_mortes', 'Ocup_caminhonete_mortes',
       'Ocup_veic_transp_pesado_mortes', 'Ocup_onibus_mortes', 'Outros_mortes',
       'Populacao', 'total_mortes', 'taxa_mun_mortes',
       'taxa_mun_pedestre_mortes', 'taxa_mun_ciclista_mortes',
       'taxa_mun_motociclista_mortes', 'taxa_mun_automovel_mortes',
       'taxa_mun_veiculo_pesado_mortes', 'taxa_mun_onibus_mortes',
       'taxa_mun_outros_mortes', 'mun_MUNNOME', 'mun_MUNNOMEX', 'mun_AMAZONIA',
       'mun_FRONTEIRA', 'mun_CAPITAL', 'mun_LATITUDE', 'mun_LONGITUDE',
       'mun_ALTITUDE', 'mun_AREA', 'mun_codigo_adotado', 'uf_SIGLA_UF',
       'uf_CODIGO_UF', 'uf_NOME_UF', 'uf_REGIAO', 'mun_coordenadas',
       'Pedestre_feridos', 'Ciclista_feridos', 'Motociclista_feridos',
       'Ocup_triciclo_motor_feridos', 'Ocup_automovel_feridos',
       'Ocup_caminhonete_feridos', 'Ocup_veic_transp_pesado_feridos',
       'Ocup_onibus_feridos', 'Outros_feridos', 'total_feridos',
       'taxa_mun_feridos', 'taxa_mun_pedestre_feridos',
       'taxa_mun_ciclista_feridos', 'taxa_mun_motociclista_feridos',
       'taxa_mun_automovel_feridos', 'taxa_mun_veiculo_pesado_feridos',
       'taxa_mun_onibus_feridos', 'taxa_mun_outros_feridos'],
      dtype='object')

In [54]:
df_acidentes = df_acidentes.drop(['Município', 'mun_MUNNOME', 'mun_MUNNOMEX', 'mun_AMAZONIA', 'mun_FRONTEIRA', 'mun_CAPITAL', 'mun_LATITUDE', 'mun_LONGITUDE',
                    'mun_ALTITUDE', 'mun_AREA', 'mun_codigo_adotado', 'uf_SIGLA_UF',
                    'uf_CODIGO_UF', 'uf_NOME_UF', 'uf_REGIAO', 'mun_coordenadas'], axis = 1)

In [55]:
df_acidentes.isna().sum()

Código IBGE                         0
ano                                 0
Região                              0
Pedestre_mortes                     0
Ciclista_mortes                     0
Motociclista_mortes                 0
Ocup_triciclo_motor_mortes          0
Ocup_automovel_mortes               0
Ocup_caminhonete_mortes             0
Ocup_veic_transp_pesado_mortes      0
Ocup_onibus_mortes                  0
Outros_mortes                       0
Populacao                           0
total_mortes                        0
taxa_mun_mortes                    10
taxa_mun_pedestre_mortes           10
taxa_mun_ciclista_mortes           10
taxa_mun_motociclista_mortes       10
taxa_mun_automovel_mortes          10
taxa_mun_veiculo_pesado_mortes     10
taxa_mun_onibus_mortes             10
taxa_mun_outros_mortes             10
Pedestre_feridos                    0
Ciclista_feridos                    0
Motociclista_feridos                0
Ocup_triciclo_motor_feridos         0
Ocup_automovel_feridos              0
Ocup_caminhonete_feridos            0
Ocup_veic_transp_pesado_feridos     0
Ocup_onibus_feridos                 0
Outros_feridos                      0
total_feridos                       0
taxa_mun_feridos                   10
taxa_mun_pedestre_feridos          10
taxa_mun_ciclista_feridos          10
taxa_mun_motociclista_feridos      10
taxa_mun_automovel_feridos         10
taxa_mun_veiculo_pesado_feridos    10
taxa_mun_onibus_feridos            10
taxa_mun_outros_feridos            10
dtype: int64

taxa é nula em alguns. Precisamos verificar o que essa taxa significa. Provavelmente deve ser a divisão pela população do município naquele ano?

In [56]:
df_populacao

        Código IBGE            mun_MUNNOME uf_SIGLA_UF  Populacao   ano
0           1100015  Alta Floresta D'Oeste          RO    33471.0  1996
1           1100023              Ariquemes          RO    68503.0  1996
2           1100031                 Cabixi          RO     8263.0  1996
3           1100049                 Cacoal          RO    72922.0  1996
4           1100056             Cerejeiras          RO    21157.0  1996
...             ...                    ...         ...        ...   ...
155955      5222005             Vianópolis          GO    14046.0  2023
155956      5222054         Vicentinópolis          GO     8776.0  2023
155957      5222203               Vila Boa          GO     3686.0  2023
155958      5222302          Vila Propício          GO     5646.0  2023
155959      5300108               Brasília          DF  2923369.0  2023

[155960 rows x 5 columns]

In [57]:
len(df_acidentes)

55700

In [58]:
df_merge_acidentes = df_acidentes.merge(df_populacao[['Código IBGE', 'Populacao', 'ano']], on=["Código IBGE", "ano"], how='left', suffixes=['_acidentes', '_populacao'])
df_merge_acidentes

,Código IBGE,ano,Região,Pedestre_mortes,Ciclista_mortes,Motociclista_mortes,Ocup_triciclo_motor_mortes,Ocup_automovel_mortes,Ocup_caminhonete_mortes,Ocup_veic_transp_pesado_mortes,Ocup_onibus_mortes,Outros_mortes,Populacao_acidentes,total_mortes,taxa_mun_mortes,taxa_mun_pedestre_mortes,taxa_mun_ciclista_mortes,taxa_mun_motociclista_mortes,taxa_mun_automovel_mortes,taxa_mun_veiculo_pesado_mortes,taxa_mun_onibus_mortes,taxa_mun_outros_mortes,Pedestre_feridos,Ciclista_feridos,Motociclista_feridos,Ocup_triciclo_motor_feridos,Ocup_automovel_feridos,Ocup_caminhonete_feridos,Ocup_veic_transp_pesado_feridos,Ocup_onibus_feridos,Outros_feridos,total_feridos,taxa_mun_feridos,taxa_mun_pedestre_feridos,taxa_mun_ciclista_feridos,taxa_mun_motociclista_feridos,taxa_mun_automovel_feridos,taxa_mun_veiculo_pesado_feridos,taxa_mun_onibus_feridos,taxa_mun_outros_feridos,Populacao_populacao
0,1100015,2010,N,2,0,5,0,0,0,0,0,0,24392,7.0,28.697900,8.199400,0.000000,20.498500,0.000000,0.000000,0.000000,0.000000,0,0,13,0,0,0,0,0,0,13.0,53.296200,0.000000,0.000000,53.296200,0.000000,0.000000,0.000000,0.000000,24392.0
1,1100023,2010,N,0,1,2,0,0,0,0,1,29,90353,33.0,36.523400,0.000000,1.106800,2.213500,0.000000,0.000000,1.106800,32.096300,0,1,37,0,1,1,0,0,3,43.0,47.591100,0.000000,1.106800,40.950500,2.213500,0.000000,0.000000,3.320300,90353.0
2,1100031,2010,N,0,0,0,0,0,0,0,0,0,6313,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,0,0,0,0,0,0,0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6313.0
3,1100049,2010,N,2,1,17,0,4,0,0,0,2,78574,26.0,33.089800,2.545400,1.272700,21.635700,5.090700,0.000000,0.000000,2.545400,50,1,5,0,0,0,0,0,1,57.0,72.543100,63.634300,1.272700,6.363400,0.000000,0.000000,0.000000,1.272700,78574.0
4,1100056,2010,N,3,0,1,0,0,0,0,0,0,17029,4.0,23.489300,17.617000,0.000000,5.872300,0.000000,0.000000,0.000000,0.000000,0,1,0,0,0,0,0,0,0,1.0,5.872300,0.000000,5.872300,0.000000,0.000000,0.000000,0.000000,0.000000,17029.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55695,5222005,2019,CO,1,0,1,0,0,0,0,0,2,13863,4.0,28.853783,7.213446,0.000000,7.213446,0.000000,0.000000,0.000000,14.426892,0,0,0,0,0,0,0,0,0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,13863.0
55696,5222054,2019,CO,0,0,0,0,2,0,0,0,2,8743,4.0,45.750886,0.000000,0.000000,0.000000,22.875443,0.000000,0.000000,22.875443,0,0,0,0,0,0,0,0,0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8743.0
55697,5222203,2019,CO,0,0,1,0,6,0,1,0,0,6171,8.0,129.638632,0.000000,0.000000,16.204829,97.228974,16.204829,0.000000,0.000000,0,0,0,0,0,0,0,0,0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6171.0
55698,5222302,2019,CO,0,0,0,0,1,0,0,0,2,5821,3.0,51.537537,0.000000,0.000000,0.000000,17.179179,0.000000,0.000000,34.358358,0,0,0,0,0,0,0,0,0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5821.0
55699,5300108,2019,CO,107,20,97,0,87,6,6,1,14,3015268,338.0,11.209617,3.548607,0.663291,3.216961,2.885316,0.198987,0.033165,0.464304,600,309,1182,7,353,9,20,10,145,2635.0,87.388584,19.898729,10.247845,39.200496,11.707085,0.663291,0.331645,4.808859,3015268.0

In [59]:
df_merge_acidentes[df_merge_acidentes['Populacao_acidentes'] != df_merge_acidentes['Populacao_populacao']][['Populacao_acidentes', 'Populacao_populacao']]

       Populacao_acidentes  Populacao_populacao
5573                 78959              78958.0
5576                  8655               8654.0
5577                 14023              14022.0
5578                 28963              28962.0
5579                 41934              41933.0
...                    ...                  ...
16300                 4723                  0.0
17325                24706              29208.0
17370                31335              26833.0
17977                95196             102789.0
18126               132871             125278.0

[2867 rows x 2 columns]

In [60]:
df_merge_acidentes_copy = df_merge_acidentes.copy()

In [61]:
df_merge_acidentes_copy['porc_mortes'] = df_merge_acidentes_copy['total_mortes']/df_merge_acidentes_copy['Populacao_acidentes'] * 100000

In [62]:
df_merge_acidentes_copy[['porc_mortes', 'taxa_mun_mortes']]

       porc_mortes  taxa_mun_mortes
0        28.697934        28.697900
1        36.523414        36.523400
2         0.000000         0.000000
3        33.089826        33.089800
4        23.489342        23.489300
...            ...              ...
55695    28.853783        28.853783
55696    45.750886        45.750886
55697   129.638632       129.638632
55698    51.537537        51.537537
55699    11.209617        11.209617

[55700 rows x 2 columns]

In [63]:
(abs(df_merge_acidentes_copy['porc_mortes'] - df_merge_acidentes_copy['taxa_mun_mortes']) <= 1).all()

False

In [64]:
df_merge_acidentes_copy[~(abs(df_merge_acidentes_copy['porc_mortes'] - df_merge_acidentes_copy['taxa_mun_mortes']) <= 1)][['porc_mortes', 'taxa_mun_mortes']]

       porc_mortes  taxa_mun_mortes
224            NaN              NaN
4503           NaN              NaN
4605           NaN              NaN
4923           NaN              NaN
5160           NaN              NaN
5794           NaN              NaN
10073          NaN              NaN
10175          NaN              NaN
10493          NaN              NaN
10730          NaN              NaN

In [65]:
df_merge_acidentes_copy['porc_mortes_pesados'] = df_merge_acidentes_copy['Ocup_veic_transp_pesado_mortes']/df_merge_acidentes_copy['Populacao_acidentes'] * 100000

In [66]:
df_merge_acidentes_copy[['porc_mortes_pesados', 'taxa_mun_veiculo_pesado_mortes']]

       porc_mortes_pesados  taxa_mun_veiculo_pesado_mortes
0                 0.000000                        0.000000
1                 0.000000                        0.000000
2                 0.000000                        0.000000
3                 0.000000                        0.000000
4                 0.000000                        0.000000
...                    ...                             ...
55695             0.000000                        0.000000
55696             0.000000                        0.000000
55697            16.204829                       16.204829
55698             0.000000                        0.000000
55699             0.198987                        0.198987

[55700 rows x 2 columns]

In [67]:
df_merge_acidentes_copy[~(abs(df_merge_acidentes_copy['porc_mortes_pesados'] - df_merge_acidentes_copy['taxa_mun_veiculo_pesado_mortes']) <= 1)][['porc_mortes_pesados', 'taxa_mun_veiculo_pesado_mortes']]

       porc_mortes_pesados  taxa_mun_veiculo_pesado_mortes
224                    NaN                             NaN
4503                   NaN                             NaN
4605                   NaN                             NaN
4923                   NaN                             NaN
5160                   NaN                             NaN
5794                   NaN                             NaN
10073                  NaN                             NaN
10175                  NaN                             NaN
10493                  NaN                             NaN
10730                  NaN                             NaN

Diferença é pequena, então provavelmente é esse o cálculo feito para chegar na taxa. Como temos valores nulos e sabemos como chegar nessas colunas, vamos recalculá-las com a Populacao do df de populacao (para padronização).

Também vamos optar por colocar em porcentagem (multiplicar divisão por 100). No original a divisão estava multiplicada por 10^5

In [68]:
df_merge_acidentes.columns

Index(['Código IBGE', 'ano', 'Região', 'Pedestre_mortes', 'Ciclista_mortes',
       'Motociclista_mortes', 'Ocup_triciclo_motor_mortes',
       'Ocup_automovel_mortes', 'Ocup_caminhonete_mortes',
       'Ocup_veic_transp_pesado_mortes', 'Ocup_onibus_mortes', 'Outros_mortes',
       'Populacao_acidentes', 'total_mortes', 'taxa_mun_mortes',
       'taxa_mun_pedestre_mortes', 'taxa_mun_ciclista_mortes',
       'taxa_mun_motociclista_mortes', 'taxa_mun_automovel_mortes',
       'taxa_mun_veiculo_pesado_mortes', 'taxa_mun_onibus_mortes',
       'taxa_mun_outros_mortes', 'Pedestre_feridos', 'Ciclista_feridos',
       'Motociclista_feridos', 'Ocup_triciclo_motor_feridos',
       'Ocup_automovel_feridos', 'Ocup_caminhonete_feridos',
       'Ocup_veic_transp_pesado_feridos', 'Ocup_onibus_feridos',
       'Outros_feridos', 'total_feridos', 'taxa_mun_feridos',
       'taxa_mun_pedestre_feridos', 'taxa_mun_ciclista_feridos',
       'taxa_mun_motociclista_feridos', 'taxa_mun_automovel_feridos',
       'taxa_mun_veiculo_pesado_feridos', 'taxa_mun_onibus_feridos',
       'taxa_mun_outros_feridos', 'Populacao_populacao'],
      dtype='object')

In [69]:
colunas_taxa = df_merge_acidentes.filter(like='taxa_').columns.tolist()
colunas_taxa

['taxa_mun_mortes',
 'taxa_mun_pedestre_mortes',
 'taxa_mun_ciclista_mortes',
 'taxa_mun_motociclista_mortes',
 'taxa_mun_automovel_mortes',
 'taxa_mun_veiculo_pesado_mortes',
 'taxa_mun_onibus_mortes',
 'taxa_mun_outros_mortes',
 'taxa_mun_feridos',
 'taxa_mun_pedestre_feridos',
 'taxa_mun_ciclista_feridos',
 'taxa_mun_motociclista_feridos',
 'taxa_mun_automovel_feridos',
 'taxa_mun_veiculo_pesado_feridos',
 'taxa_mun_onibus_feridos',
 'taxa_mun_outros_feridos']

In [70]:
colunas_sem_taxa = df_merge_acidentes.columns[~df_merge_acidentes.columns.str.startswith('taxa_')].tolist()
colunas_sem_taxa

['Código IBGE',
 'ano',
 'Região',
 'Pedestre_mortes',
 'Ciclista_mortes',
 'Motociclista_mortes',
 'Ocup_triciclo_motor_mortes',
 'Ocup_automovel_mortes',
 'Ocup_caminhonete_mortes',
 'Ocup_veic_transp_pesado_mortes',
 'Ocup_onibus_mortes',
 'Outros_mortes',
 'Populacao_acidentes',
 'total_mortes',
 'Pedestre_feridos',
 'Ciclista_feridos',
 'Motociclista_feridos',
 'Ocup_triciclo_motor_feridos',
 'Ocup_automovel_feridos',
 'Ocup_caminhonete_feridos',
 'Ocup_veic_transp_pesado_feridos',
 'Ocup_onibus_feridos',
 'Outros_feridos',
 'total_feridos',
 'Populacao_populacao']

In [71]:
df_merge_acidentes['taxa_mun_mortes_antes'] = df_merge_acidentes['taxa_mun_mortes']

In [72]:

correspondencia = {
    'taxa_mun_mortes': 'total_mortes',
    'taxa_mun_pedestre_mortes': 'Pedestre_mortes',
    'taxa_mun_ciclista_mortes': 'Ciclista_mortes',
    'taxa_mun_motociclista_mortes': 'Motociclista_mortes',
    'taxa_mun_triciclo_mortes': 'Ocup_triciclo_motor_mortes',
    'taxa_mun_automovel_mortes': 'Ocup_automovel_mortes',
    'taxa_mun_caminhonete_mortes': 'Ocup_caminhonete_mortes',
    'taxa_mun_veiculo_pesado_mortes': 'Ocup_veic_transp_pesado_mortes',
    'taxa_mun_onibus_mortes': 'Ocup_onibus_mortes',
    'taxa_mun_outros_mortes': 'Outros_mortes',
    'taxa_mun_feridos': 'total_feridos',
    'taxa_mun_pedestre_feridos': 'Pedestre_feridos',
    'taxa_mun_ciclista_feridos': 'Ciclista_feridos',
    'taxa_mun_motociclista_feridos': 'Motociclista_feridos',
    'taxa_mun_triciclo_feridos': 'Ocup_triciclo_motor_feridos',
    'taxa_mun_automovel_feridos': 'Ocup_automovel_feridos',
    'taxa_mun_caminhonete_feridos': 'Ocup_caminhonete_feridos',
    'taxa_mun_veiculo_pesado_feridos': 'Ocup_veic_transp_pesado_feridos',
    'taxa_mun_onibus_feridos': 'Ocup_onibus_feridos',
    'taxa_mun_outros_feridos': 'Outros_feridos',
}

for taxa_col, num_col in correspondencia.items():
    # para evitar divisão por zero, se populacao for zero (há casos)
    df_merge_acidentes[taxa_col] = np.where(df_merge_acidentes['Populacao_populacao'] != 0, 
                                            df_merge_acidentes[num_col] / df_merge_acidentes['Populacao_populacao'] * 100, 
                                            0)

In [73]:
df_merge_acidentes[df_merge_acidentes['Populacao_populacao'] == 0][['Populacao_populacao', 'Populacao_acidentes', 'total_mortes', 'total_feridos']]

       Populacao_populacao  Populacao_acidentes  total_mortes  total_feridos
224                    0.0                    0           0.0            0.0
4503                   0.0                    0           0.0            0.0
4605                   0.0                    0           0.0            0.0
4923                   0.0                    0           0.0            0.0
5160                   0.0                    0           0.0            0.0
5794                   0.0                    0           0.0            0.0
10073                  0.0                    0           0.0            0.0
10175                  0.0                    0           0.0            0.0
10493                  0.0                    0           0.0            0.0
10730                  0.0                    0           0.0            0.0
11364                  0.0                15018           0.0            0.0
15643                  0.0                 9416           0.0            0.0
15745                  0.0                11136           0.0            0.0
16063                  0.0                 2578           0.0            0.0
16300                  0.0                 4723           0.0            0.0

In [74]:
df_merge_acidentes.isna().sum()

Código IBGE                         0
ano                                 0
Região                              0
Pedestre_mortes                     0
Ciclista_mortes                     0
Motociclista_mortes                 0
Ocup_triciclo_motor_mortes          0
Ocup_automovel_mortes               0
Ocup_caminhonete_mortes             0
Ocup_veic_transp_pesado_mortes      0
Ocup_onibus_mortes                  0
Outros_mortes                       0
Populacao_acidentes                 0
total_mortes                        0
taxa_mun_mortes                     0
taxa_mun_pedestre_mortes            0
taxa_mun_ciclista_mortes            0
taxa_mun_motociclista_mortes        0
taxa_mun_automovel_mortes           0
taxa_mun_veiculo_pesado_mortes      0
taxa_mun_onibus_mortes              0
taxa_mun_outros_mortes              0
Pedestre_feridos                    0
Ciclista_feridos                    0
Motociclista_feridos                0
Ocup_triciclo_motor_feridos         0
Ocup_automovel_feridos              0
Ocup_caminhonete_feridos            0
Ocup_veic_transp_pesado_feridos     0
Ocup_onibus_feridos                 0
Outros_feridos                      0
total_feridos                       0
taxa_mun_feridos                    0
taxa_mun_pedestre_feridos           0
taxa_mun_ciclista_feridos           0
taxa_mun_motociclista_feridos       0
taxa_mun_automovel_feridos          0
taxa_mun_veiculo_pesado_feridos     0
taxa_mun_onibus_feridos             0
taxa_mun_outros_feridos             0
Populacao_populacao                 0
taxa_mun_mortes_antes              10
taxa_mun_triciclo_mortes            0
taxa_mun_caminhonete_mortes         0
taxa_mun_triciclo_feridos           0
taxa_mun_caminhonete_feridos        0
dtype: int64

In [75]:
df_merge_acidentes[~(abs(df_merge_acidentes['taxa_mun_mortes_antes'] - df_merge_acidentes['taxa_mun_mortes']*1000) <= 1)][['total_mortes', 'Populacao_populacao', 'Populacao_acidentes', 'taxa_mun_mortes', 'taxa_mun_mortes_antes']]

,total_mortes,Populacao_populacao,Populacao_acidentes,taxa_mun_mortes,taxa_mun_mortes_antes
224,0.0,0.0,0,0.000000,NaN
4503,0.0,0.0,0,0.000000,NaN
4605,0.0,0.0,0,0.000000,NaN
4923,0.0,0.0,0,0.000000,NaN
5160,0.0,0.0,0,0.000000,NaN
5794,0.0,0.0,0,0.000000,NaN
6034,1.0,14226.0,11508,0.007029,8.6896
6100,1.0,11869.0,10205,0.008425,9.7991
6110,1.0,14571.0,12337,0.006863,8.1057
10073,0.0,0.0,0,0.000000,NaN
10175,0.0,0.0,0,0.000000,NaN
10493,0.0,0.0,0,0.000000,NaN
10730,0.0,0.0,0,0.000000,NaN
11604,1.0,11703.0,14407,0.008545,6.9411
11806,11.0,52059.0,49355,0.021130,22.2875
15559,10.0,60374.0,49238,0.016563,20.3095
15592,13.0,52166.0,42750,0.024920,30.4094
16243,5.0,14939.0,13358,0.033469,37.4308
16265,5.0,20855.0,19974,0.023975,25.0325
16269,11.0,20348.0,18087,0.054059,60.8172
17325,7.0,29208.0,24706,0.023966,28.3332
18126,25.0,125278.0,132871,0.019956,18.8152

In [76]:
1/14226.0 * 100

0.0070293828201883875

In [77]:
(1/11508) * 100000

8.689607229753216

In [78]:
df_merge_acidentes

,Código IBGE,ano,Região,Pedestre_mortes,Ciclista_mortes,Motociclista_mortes,Ocup_triciclo_motor_mortes,Ocup_automovel_mortes,Ocup_caminhonete_mortes,Ocup_veic_transp_pesado_mortes,Ocup_onibus_mortes,Outros_mortes,Populacao_acidentes,total_mortes,taxa_mun_mortes,taxa_mun_pedestre_mortes,taxa_mun_ciclista_mortes,taxa_mun_motociclista_mortes,taxa_mun_automovel_mortes,taxa_mun_veiculo_pesado_mortes,taxa_mun_onibus_mortes,taxa_mun_outros_mortes,Pedestre_feridos,Ciclista_feridos,Motociclista_feridos,Ocup_triciclo_motor_feridos,Ocup_automovel_feridos,Ocup_caminhonete_feridos,Ocup_veic_transp_pesado_feridos,Ocup_onibus_feridos,Outros_feridos,total_feridos,taxa_mun_feridos,taxa_mun_pedestre_feridos,taxa_mun_ciclista_feridos,taxa_mun_motociclista_feridos,taxa_mun_automovel_feridos,taxa_mun_veiculo_pesado_feridos,taxa_mun_onibus_feridos,taxa_mun_outros_feridos,Populacao_populacao,taxa_mun_mortes_antes,taxa_mun_triciclo_mortes,taxa_mun_caminhonete_mortes,taxa_mun_triciclo_feridos,taxa_mun_caminhonete_feridos
0,1100015,2010,N,2,0,5,0,0,0,0,0,0,24392,7.0,0.028698,0.008199,0.000000,0.020499,0.000000,0.000000,0.000000,0.000000,0,0,13,0,0,0,0,0,0,13.0,0.053296,0.000000,0.000000,0.053296,0.000000,0.000000,0.000000,0.000000,24392.0,28.697900,0.0,0.000000,0.000000,0.000000
1,1100023,2010,N,0,1,2,0,0,0,0,1,29,90353,33.0,0.036523,0.000000,0.001107,0.002214,0.000000,0.000000,0.001107,0.032096,0,1,37,0,1,1,0,0,3,43.0,0.047591,0.000000,0.001107,0.040950,0.001107,0.000000,0.000000,0.003320,90353.0,36.523400,0.0,0.000000,0.000000,0.001107
2,1100031,2010,N,0,0,0,0,0,0,0,0,0,6313,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,0,0,0,0,0,0,0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6313.0,0.000000,0.0,0.000000,0.000000,0.000000
3,1100049,2010,N,2,1,17,0,4,0,0,0,2,78574,26.0,0.033090,0.002545,0.001273,0.021636,0.005091,0.000000,0.000000,0.002545,50,1,5,0,0,0,0,0,1,57.0,0.072543,0.063634,0.001273,0.006363,0.000000,0.000000,0.000000,0.001273,78574.0,33.089800,0.0,0.000000,0.000000,0.000000
4,1100056,2010,N,3,0,1,0,0,0,0,0,0,17029,4.0,0.023489,0.017617,0.000000,0.005872,0.000000,0.000000,0.000000,0.000000,0,1,0,0,0,0,0,0,0,1.0,0.005872,0.000000,0.005872,0.000000,0.000000,0.000000,0.000000,0.000000,17029.0,23.489300,0.0,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55695,5222005,2019,CO,1,0,1,0,0,0,0,0,2,13863,4.0,0.028854,0.007213,0.000000,0.007213,0.000000,0.000000,0.000000,0.014427,0,0,0,0,0,0,0,0,0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,13863.0,28.853783,0.0,0.000000,0.000000,0.000000
55696,5222054,2019,CO,0,0,0,0,2,0,0,0,2,8743,4.0,0.045751,0.000000,0.000000,0.000000,0.022875,0.000000,0.000000,0.022875,0,0,0,0,0,0,0,0,0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8743.0,45.750886,0.0,0.000000,0.000000,0.000000
55697,5222203,2019,CO,0,0,1,0,6,0,1,0,0,6171,8.0,0.129639,0.000000,0.000000,0.016205,0.097229,0.016205,0.000000,0.000000,0,0,0,0,0,0,0,0,0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6171.0,129.638632,0.0,0.000000,0.000000,0.000000
55698,5222302,2019,CO,0,0,0,0,1,0,0,0,2,5821,3.0,0.051538,0.000000,0.000000,0.000000,0.017179,0.000000,0.000000,0.034358,0,0,0,0,0,0,0,0,0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5821.0,51.537537,0.0,0.000000,0.000000,0.000000
55699,5300108,2019,CO,107,20,97,0,87,6,6,1,14,3015268,338.0,0.011210,0.003549,0.000663,0.003217,0.002885,0.000199,0.000033,0.000464,600,309,1182,7,353,9,20,10,145,2635.0,0.087389,0.019899,0.010248,0.039200,0.011707,0.000663,0.000332,0.004809,3015268.0,11.209617,0.0,0.000199,0.000232,0.000298

In [79]:
df_merge_acidentes

,Código IBGE,ano,Região,Pedestre_mortes,Ciclista_mortes,Motociclista_mortes,Ocup_triciclo_motor_mortes,Ocup_automovel_mortes,Ocup_caminhonete_mortes,Ocup_veic_transp_pesado_mortes,Ocup_onibus_mortes,Outros_mortes,Populacao_acidentes,total_mortes,taxa_mun_mortes,taxa_mun_pedestre_mortes,taxa_mun_ciclista_mortes,taxa_mun_motociclista_mortes,taxa_mun_automovel_mortes,taxa_mun_veiculo_pesado_mortes,taxa_mun_onibus_mortes,taxa_mun_outros_mortes,Pedestre_feridos,Ciclista_feridos,Motociclista_feridos,Ocup_triciclo_motor_feridos,Ocup_automovel_feridos,Ocup_caminhonete_feridos,Ocup_veic_transp_pesado_feridos,Ocup_onibus_feridos,Outros_feridos,total_feridos,taxa_mun_feridos,taxa_mun_pedestre_feridos,taxa_mun_ciclista_feridos,taxa_mun_motociclista_feridos,taxa_mun_automovel_feridos,taxa_mun_veiculo_pesado_feridos,taxa_mun_onibus_feridos,taxa_mun_outros_feridos,Populacao_populacao,taxa_mun_mortes_antes,taxa_mun_triciclo_mortes,taxa_mun_caminhonete_mortes,taxa_mun_triciclo_feridos,taxa_mun_caminhonete_feridos
0,1100015,2010,N,2,0,5,0,0,0,0,0,0,24392,7.0,0.028698,0.008199,0.000000,0.020499,0.000000,0.000000,0.000000,0.000000,0,0,13,0,0,0,0,0,0,13.0,0.053296,0.000000,0.000000,0.053296,0.000000,0.000000,0.000000,0.000000,24392.0,28.697900,0.0,0.000000,0.000000,0.000000
1,1100023,2010,N,0,1,2,0,0,0,0,1,29,90353,33.0,0.036523,0.000000,0.001107,0.002214,0.000000,0.000000,0.001107,0.032096,0,1,37,0,1,1,0,0,3,43.0,0.047591,0.000000,0.001107,0.040950,0.001107,0.000000,0.000000,0.003320,90353.0,36.523400,0.0,0.000000,0.000000,0.001107
2,1100031,2010,N,0,0,0,0,0,0,0,0,0,6313,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,0,0,0,0,0,0,0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6313.0,0.000000,0.0,0.000000,0.000000,0.000000
3,1100049,2010,N,2,1,17,0,4,0,0,0,2,78574,26.0,0.033090,0.002545,0.001273,0.021636,0.005091,0.000000,0.000000,0.002545,50,1,5,0,0,0,0,0,1,57.0,0.072543,0.063634,0.001273,0.006363,0.000000,0.000000,0.000000,0.001273,78574.0,33.089800,0.0,0.000000,0.000000,0.000000
4,1100056,2010,N,3,0,1,0,0,0,0,0,0,17029,4.0,0.023489,0.017617,0.000000,0.005872,0.000000,0.000000,0.000000,0.000000,0,1,0,0,0,0,0,0,0,1.0,0.005872,0.000000,0.005872,0.000000,0.000000,0.000000,0.000000,0.000000,17029.0,23.489300,0.0,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55695,5222005,2019,CO,1,0,1,0,0,0,0,0,2,13863,4.0,0.028854,0.007213,0.000000,0.007213,0.000000,0.000000,0.000000,0.014427,0,0,0,0,0,0,0,0,0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,13863.0,28.853783,0.0,0.000000,0.000000,0.000000
55696,5222054,2019,CO,0,0,0,0,2,0,0,0,2,8743,4.0,0.045751,0.000000,0.000000,0.000000,0.022875,0.000000,0.000000,0.022875,0,0,0,0,0,0,0,0,0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8743.0,45.750886,0.0,0.000000,0.000000,0.000000
55697,5222203,2019,CO,0,0,1,0,6,0,1,0,0,6171,8.0,0.129639,0.000000,0.000000,0.016205,0.097229,0.016205,0.000000,0.000000,0,0,0,0,0,0,0,0,0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6171.0,129.638632,0.0,0.000000,0.000000,0.000000
55698,5222302,2019,CO,0,0,0,0,1,0,0,0,2,5821,3.0,0.051538,0.000000,0.000000,0.000000,0.017179,0.000000,0.000000,0.034358,0,0,0,0,0,0,0,0,0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5821.0,51.537537,0.0,0.000000,0.000000,0.000000
55699,5300108,2019,CO,107,20,97,0,87,6,6,1,14,3015268,338.0,0.011210,0.003549,0.000663,0.003217,0.002885,0.000199,0.000033,0.000464,600,309,1182,7,353,9,20,10,145,2635.0,0.087389,0.019899,0.010248,0.039200,0.011707,0.000663,0.000332,0.004809,3015268.0,11.209617,0.0,0.000199,0.000232,0.000298

In [81]:
df_merge_acidentes = df_merge_acidentes.drop(['taxa_mun_mortes_antes'], axis = 1)

In [83]:
df_merge_acidentes.isna().sum().sum()

0

Diferença devido à diferença na população

In [87]:
df_merge_acidentes.to_csv(pasta_dados + 'tratados/simu_acidentes_de_transportes.csv', index=False)